# Generated by Django 4.1.10 on 2023-07-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("image_url", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=30)),
                ("type", models.CharField(blank=True, max_length=30, null=True)),
                ("ac_bed_price", models.FloatField(blank=True, null=True)),
                ("non_ac_bed_price", models.FloatField(blank=True, null=True)),
                ("room_price", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
